#!/bin/sh
xctool -workspace Example.xcworkspace -scheme Example-en -sdk iphonesimulator test
xctool -workspace Example.xcworkspace -scheme Example-ja -sdk iphonesimulator test
xctool -workspace Example.xcworkspace -scheme Example-fr -sdk iphonesimulator test
